version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017 
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db  

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local 
